In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [2]:
A = np.array([[0.9, 0.07, 0.02, 0.01], [0, 0.93, 0.05, 0.02], [0, 0, 0.85, 0.15], [0, 0, 0, 1]])

In [10]:
t = np.array([0.85, 0.10, 0.05, 0])
A.ndim

(4, 4)

In [12]:
print(A.T @ t.T)
np.dot(A.T, t.T)

[0.765  0.1525 0.0645 0.018 ]


array([0.765 , 0.1525, 0.0645, 0.018 ])

In [8]:
P = np.array([[6,5,3,1], [3,6,2,2], [3,4,3,1]])

In [9]:
S = np.array([[1.5, 1], [2, 2.5], [5, 4.5], [16, 17]])

In [10]:
P@S


array([[ 50. ,  49. ],
       [ 58.5,  61. ],
       [ 43.5,  43.5]])

In [11]:
def f(x):
    if x <= 1/2:
        return 2 * x
    if x > 1/2:
        return 2*x - 1

In [12]:
f(1/10)

0.2

In [13]:
x = 1/10
for i in range(80):
    print(x)
    x = f(x)

0.1
0.2
0.4
0.8
0.6000000000000001
0.20000000000000018
0.40000000000000036
0.8000000000000007
0.6000000000000014
0.20000000000000284
0.4000000000000057
0.8000000000000114
0.6000000000000227
0.20000000000004547
0.40000000000009095
0.8000000000001819
0.6000000000003638
0.2000000000007276
0.4000000000014552
0.8000000000029104
0.6000000000058208
0.20000000001164153
0.40000000002328306
0.8000000000465661
0.6000000000931323
0.20000000018626451
0.40000000037252903
0.8000000007450581
0.6000000014901161
0.20000000298023224
0.4000000059604645
0.800000011920929
0.6000000238418579
0.20000004768371582
0.40000009536743164
0.8000001907348633
0.6000003814697266
0.20000076293945312
0.40000152587890625
0.8000030517578125
0.600006103515625
0.20001220703125
0.4000244140625
0.800048828125
0.60009765625
0.2001953125
0.400390625
0.80078125
0.6015625
0.203125
0.40625
0.8125
0.625
0.25
0.5
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [6]:
np.ones([3,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [7]:
np.full([3, 3], 'lol'
       )

array([['lol', 'lol', 'lol'],
       ['lol', 'lol', 'lol'],
       ['lol', 'lol', 'lol']],
      dtype='<U3')

In [8]:
np.full([1,1], 1
       )

array([[1]])

In [10]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [11]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,3)

array([1, 2])

In [15]:
np.arange(1, 4, 2)

array([1, 3])

In [16]:
np.arange(1, 4, 0.3)

array([ 1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7])

In [17]:
np.linspace(1, 4, 10)

array([ 1.        ,  1.33333333,  1.66666667,  2.        ,  2.33333333,
        2.66666667,  3.        ,  3.33333333,  3.66666667,  4.        ])

In [19]:
np.linspace(1, 4, 10, endpoint=False)

array([ 1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7])

In [20]:
x = np.arange(10)

In [22]:
x.reshape([2, 5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.reshape(x, [2, 5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
np.random.random((3,1))

array([[ 0.56605362],
       [ 0.69599888],
       [ 0.20031557]])

In [29]:
np.random.randint(1,10,(3,1))

array([[3],
       [4],
       [3]])

In [22]:
X = np.random.normal(2, 1, size=(2,2))
X

array([[-0.0663736 ,  3.6322353 ],
       [ 0.79089624,  1.53873944]])

In [23]:
X.mean()

1.473874343874708

In [35]:
X

array([[ 2.44356542,  1.4585499 ],
       [ 1.91747351,  1.79006779]])

In [36]:
X.min()

1.4585499032479279

In [37]:
X.max()

2.4435654161515141

In [42]:
(X > 0)

array([[ True,  True],
       [ True,  True]], dtype=bool)

In [43]:
(X > 0).sum()

4

In [51]:
np.arange(2, 33, 2).reshape(4,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [3]:
a = np.arange(2,33, 4).reshape(2, 4)

In [4]:
a

array([[ 2,  6, 10, 14],
       [18, 22, 26, 30]])

In [6]:
a[1,3]

30

In [7]:
a[1,3] = 999

In [8]:
a

array([[  2,   6,  10,  14],
       [ 18,  22,  26, 999]])

In [11]:
np.delete(a, [1,3], axis=1)

array([[ 2, 10],
       [18, 26]])

In [13]:
np.delete(a, [0,1], axis=0)

array([], shape=(0, 4), dtype=int64)

In [17]:
b = np.array([1,2,3])
np.append(b, 4)

array([1, 2, 3, 4])

In [21]:
np.append(a, [[0,0,0,0]], axis=0)

array([[  2,   6,  10,  14],
       [ 18,  22,  26, 999],
       [  0,   0,   0,   0]])

In [28]:
c = np.array([1,2,3])
np.insert(c, 1, [6, 4])

array([1, 6, 4, 2, 3])

In [36]:
d = np.array([[1,2,3], [4, 5, 6]])
np.insert(d, 1, 5, axis=1)

array([[1, 5, 2, 3],
       [4, 5, 5, 6]])

In [43]:
x = np.array([1,2])
y = np.array([[3,4], [5, 6]])
np.vstack((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
np.hstack((x.reshape(2,1), y))

array([[1, 3, 4],
       [2, 5, 6]])

In [55]:
z = np.array([['a', 'b']])
np.vstack((z, y))

array([['a', 'b'],
       ['3', '4'],
       ['5', '6']],
      dtype='<U21')

In [124]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
a[0:2, 1:3]

array([[1, 2],
       [6, 7]])

In [65]:
b = a[0:2]

In [64]:
a[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
b[1,1] = 99999
b

array([[    0,     1,     2,     3,     4],
       [    5, 99999,     7,     8,     9]])

In [67]:
a

array([[    0,     1,     2,     3,     4],
       [    5, 99999,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19]])

In [73]:
c = np.copy(b[:,:])
c[0,0] = -12222
c

array([[-12222,      1,      2,      3,      4],
       [     5,  99999,      7,      8,      9]])

In [74]:
b

array([[    0,     1,     2,     3,     4],
       [    5, 99999,     7,     8,     9]])

In [75]:
np.diag(a)

array([    0, 99999,    12,    18])

In [76]:
np.diag(a, k=1)

array([ 1,  7, 13, 19])

In [78]:
a[1,0] = 0
np.unique(a)

array([    0,     1,     2,     3,     4,     7,     8,     9,    10,
          11,    12,    13,    14,    15,    16,    17,    18,    19, 99999])

In [86]:
a[(a < 3) & (a>1)]

array([2])

In [87]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
np.intersect1d(x,y)

array([2, 4])

In [88]:
np.setdiff1d(x,y)

array([1, 3, 5])

In [89]:
np.setdiff1d(y, x)

array([6, 7, 8])

In [90]:
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
np.sort(np.random.randint(1, 11, size=(10,2)))

array([[ 2,  5],
       [ 4,  4],
       [ 5, 10],
       [ 2,  5],
       [ 1,  1],
       [ 4,  5],
       [ 4,  8],
       [ 6,  7],
       [ 1,  9],
       [ 2,  4]])

In [96]:
np.sort(np.random.randint(1, 11, size=(5,5)), axis=1)

array([[ 3,  4,  6,  7, 10],
       [ 1,  2,  4,  5, 10],
       [ 1,  5,  9,  9, 10],
       [ 3,  6,  8,  8, 10],
       [ 2,  4,  6,  6, 10]])

In [97]:
np.sort(np.random.randint(1, 11, size=(5,5)), axis=0)

array([[ 3,  4,  3,  2,  3],
       [ 4,  4,  4,  5,  4],
       [ 6,  9,  4,  5,  5],
       [ 6,  9,  7,  9,  8],
       [ 9, 10, 10, 10, 10]])

In [105]:
np.array([1,2,3]) + np.array([1,1,1])

array([2, 3, 4])

In [106]:
np.add(np.array([1,2,3]), np.array([1,1,1]))

array([2, 3, 4])

In [110]:
np.array([1,2,3]).reshape(3,1) + np.array([1,1,1])

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [112]:
np.array([1,2,3]).reshape(3,1) + np.array([1,1,1,1,1,1]).reshape(3,2)

array([[2, 2],
       [3, 3],
       [4, 4]])

In [113]:
np.exp(np.array([1,2]))

array([ 2.71828183,  7.3890561 ])

In [121]:
np.mean([[1,2,3],[4,5,6]], axis = 0)

array([ 2.5,  3.5,  4.5])

In [117]:
np.std([1,2,3], axis=0)

0.81649658092772603

In [118]:
np.array([[1,2], [3,4]]) * 10

array([[10, 20],
       [30, 40]])

In [20]:
np.dot(np.array([1,2]), np.array([1,2]))

5

In [5]:
np.array([1,2]).shape

(2,)

In [7]:
np.array([1,2]) * np.array([1,2])

array([1, 4])

In [16]:
np.array([1,2]) @ np.array([1,2])

5

In [10]:
a1 = np.array([1,2,3])
b1 = a1[:, None]

In [14]:
a1 * b1

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])